language: android

#before_cache:
# - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
# - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#
#cache:
#  directories:
#  - $HOME/.gradle/caches/
#  - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=P
    - ANDROID_BUILD_TOOLS=28-rc2

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-26
#    - sys-img-armeabi-v7a-android-17

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in travlog.jks.enc -out travlog.jks
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
  - chmod +x *.sh

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-$ANDROID_API" # Latest platform required by SDK tools

script: "sh ./build.sh"

branches:
  only:
    - staging
    - master

deploy:
  provider: script
  script: "sh ./deploy.sh"
  on:
    branch:
      - staging
      - master
